// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9UCUxfjTndZxItHf-oEIKwNdGwj4-Jjk',
    appId: '1:1025493387352:web:a6364c4872602f8d05622d',
    messagingSenderId: '1025493387352',
    projectId: 'beta-project-60585',
    authDomain: 'beta-project-60585.firebaseapp.com',
    storageBucket: 'beta-project-60585.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFM3FBjmzoLDjnX8aGWPpJued-OspTYaY',
    appId: '1:1025493387352:android:11dc56dee3a9cb4c05622d',
    messagingSenderId: '1025493387352',
    projectId: 'beta-project-60585',
    storageBucket: 'beta-project-60585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkTyFHyz6VzED4EBRQ9Kwl30MI9jha3I',
    appId: '1:1025493387352:ios:0f3563ff2275f46405622d',
    messagingSenderId: '1025493387352',
    projectId: 'beta-project-60585',
    storageBucket: 'beta-project-60585.appspot.com',
    iosBundleId: 'com.example.betaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkTyFHyz6VzED4EBRQ9Kwl30MI9jha3I',
    appId: '1:1025493387352:ios:0f3563ff2275f46405622d',
    messagingSenderId: '1025493387352',
    projectId: 'beta-project-60585',
    storageBucket: 'beta-project-60585.appspot.com',
    iosBundleId: 'com.example.betaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9UCUxfjTndZxItHf-oEIKwNdGwj4-Jjk',
    appId: '1:1025493387352:web:346a0d8ac69af28105622d',
    messagingSenderId: '1025493387352',
    projectId: 'beta-project-60585',
    authDomain: 'beta-project-60585.firebaseapp.com',
    storageBucket: 'beta-project-60585.appspot.com',
  );
}
